version: '3.9'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    env_file:
      - backend/.env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  nodejs:
    image: node:12-alpine
    depends_on:
      - postgres
    volumes:
      - './backend/:/backend/'
    command: sh -c "cd /backend/ && yarn && yarn run watch"
    expose: [3000]
    ports:
      - '3000:3000'

  nginx:
    image: nginx
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./docker/nginx/sites-available:/etc/nginx/sites-enabled/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always


volumes:
  postgres:
